# Azure DevOps Pipeline for Maven Project using Java 17

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'  
      jdkSourceOption: 'PreInstalled'  

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      goals: 'clean test package'  # Ensure tests execute

  - script: |
      echo "Checking test reports directory..."
      ls -R target/surefire-reports || echo "No reports found!"
    displayName: 'Debug: Check Surefire Reports'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)/**/target/surefire-reports/TEST-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: 'Maven Unit Tests'
