# Azure DevOps Pipeline for Maven Project using Java 17

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'  
      jdkSourceOption: 'PreInstalled'  

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true  # Ensures results are captured
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
      goals: 'clean test package'  # Runs tests before packaging

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: 'Maven Unit Tests'
